#!/bin/bash
#  -*- sh -*-

: << =cut

=head1 NAME

odometer - Plugin to monitor your Tesla odometer

=head1 CONFIGURATION

This is a wildcard plugin. To monitor a car, link tesla_odometer_<vin>
to this file. For example:

  ln -s /usr/share/munin/plugins/tesla_odometer_ \
        /etc/munin/plugins/tesla_odometer_abcdefghijklm123456
        
Will monitor odometer of a car with VIN abcdefghijklm123456

=head1 AUTHOR

Gandalf <gandalf@hive.io>

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. "$MUNIN_LIBDIR/plugins/plugin.sh"

VIN=${0##*tesla_odometer_}

case $1 in
    autoconf)
        if [ -r /var/run/munin/tesla_status.txt ]; then
                echo yes
                exit 0
        else
                echo "no (API output not found)"
                exit 0
        fi
        ;;
    config)
        title=${VIN}
            if [[ "$nickname" ]]; then
                title="$nickname"
            fi
        echo "graph_title Tesla ${title} Odometer"
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel Odometer (km)'
        echo 'graph_scale no'
        echo 'graph_category system'
        echo 'odometer.label Odometer'
	echo 'odometer.draw AREA'
        print_warning odometer
        print_critical odometer
        exit 0
        ;;
esac

echo -n "odometer.value "
value=$( cat /var/run/munin/tesla_status.txt | /usr/bin/jq '. | select( .vin == "'${VIN}'" ) .vehicle_state.odometer' )
km_value=$( bc -l <<<"1.60934 * $value" )
echo $km_value
