#!/bin/bash
#  -*- sh -*-

: << =cut

=head1 NAME

tesla_climate_ - Wildcard-plugin to monior your Tesla car climate

=head1 CONFIGURATION

This is a wildcard plugin. To monitor a car, link tesla_climate_<vin>
to this file. For example:

  ln -s /usr/share/munin/plugins/tesla_climate_ \
        /etc/munin/plugins/tesla_climate_abcdefghijklm123456
        
Will monitor climate of a car with VIN abcdefghijklm123456

=head1 AUTHOR

Gandalf <gandalf@hive.io>

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. "$MUNIN_LIBDIR/plugins/plugin.sh"

VIN=${0##*tesla_climate_}

case $1 in
    autoconf)
	if [ -r /var/run/munin/tesla_status.txt ]; then
		echo yes
		exit 0
	else
		echo "no (API output not found)"
		exit 0
	fi
	;;
    config)
        title=${VIN}
	    if [[ "$nickname" ]]; then
		title="$nickname"
	    fi
        echo "graph_title Tesla ${title} Climate"
        echo 'graph_args --base 1000'
        echo 'graph_vlabel Temperature (C)'
        echo 'graph_scale no'
        echo 'graph_category system'
        echo 'graph_info This graph shows temp.'
        echo 'driver_temp_setting.label driver_temp_setting'
        echo 'driver_temp_setting.info Driver temperature setting'
        echo 'passenger_temp_setting.label passenger_temp_setting'
        echo 'passenger_temp_setting.info Passenger temperature setting'
        echo 'inside_temp.label inside_temp'
        echo 'inside_temp.info Inside temperature'
        echo 'outside_temp.label outside_temp'
        echo 'outside_temp.info Outside temperature'
        exit 0
        ;;
esac

echo -n "driver_temp_setting.value "
dts=$( cat /var/run/munin/tesla_status.txt | /usr/bin/jq '. | select( .vin == "'${VIN}'" ) .climate_state.driver_temp_setting' )
echo $dts

echo -n "passenger_temp_setting.value "
pts=$( cat /var/run/munin/tesla_status.txt | /usr/bin/jq '. | select( .vin == "'${VIN}'" ) .climate_state.passenger_temp_setting' )
echo $pts

echo -n "inside_temp.value "
it=$( cat /var/run/munin/tesla_status.txt | /usr/bin/jq '. | select( .vin == "'${VIN}'" ) .climate_state.inside_temp' )
echo $it

echo -n "outside_temp.value "
ot=$( cat /var/run/munin/tesla_status.txt | /usr/bin/jq '. | select( .vin == "'${VIN}'" ) .climate_state.outside_temp' )
echo $ot
